### ISSUE TITLE
Skin Shader for Emily

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#10]
As the guest mentioned on Monday, we should begin our investigation into skin shaders by setting up a single-light scene with Emily, and adjusting the subsurface scattering to produce a "gummy" look.
* This should probably be done in Renderman, which will require working in lab for the time being.

**Comment by mark-craig** [comment]
Sara, can we expect this to be pretty much finalized by Friday? It seems like you're really close.

**Comment by mark-craig** [comment]
Hmm, decided to take a look at the Emily2015 file that you've pushed. All the file node references were absolute paths on your drive, so I went ahead and made them all local to the project (starting directory for textures should be images/,,,, rather than C:/Users/....)

Still getting some errors when I open the file, but it looks like something to do with RIS so it may be irrelevant?
![image](https://cloud.githubusercontent.com/assets/4493801/6471029/ab43d04c-c19c-11e4-983a-e0f4fe3d2323.png)
Here is a quick render on my system with a quick environment light taken from the renderman shelf. It looks really good to me, but do you notice anything that isn't being loaded correctly?
![image](https://cloud.githubusercontent.com/assets/4493801/6471064/e8e583c8-c19c-11e4-98aa-f9971453603e.png)

**Comment by mark-craig** [comment]
Also, I notice that you changed the geometry on the left eyeball so that about 1/3 of the sphere is completely flat. My concern is that the eye will no longer rotate correctly with the rig if it is not a perfect sphere. You also appear to have hidden the face rig in some way, and I can't figure out how to unhide it. So the result may be less problematic with that, but here is what happens when I just rotate the eyeball upwards...

![image](https://cloud.githubusercontent.com/assets/4493801/6471108/38b0f66c-c19d-11e4-90e9-cbe5167dd03e.png)

**Comment by SaraSweer** [comment]
It looks fine to me. I don't know what those references are.

Also, yes, the geometry of the eyeball has been altered to create more
believable eyes. A cornea will also be added that is a glass material and
will surround the eye, being roughly sphere.

**Comment by mark-craig** [comment]
Hmm, OK. So the idea is that the cornea will simulate lens distortion and reflection? That seems good, but I'm still concerned that it will be too large and the gap will still be visible. Also, what happened to the eye rig and does it still work correctly with the geometry changes?



—
Mark Craig

**Comment by SaraSweer** [comment]
It's better explained by this image:
http://rendermansite.pixar.com/ca_twopointo_cms_data/images/10816_18952.jpg
As for the gap...I'll have to troubleshoot that. It's an issue with the
size of our eye/pupil.
And tbh I have no idea about the rig there were two sets of geometry
representing the same right eye and I had to delete one to be able to work
on the other.

**Comment by mark-craig** [comment]
Marking as closed :)
