### ISSUE TITLE
Update sound for next week

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#12]
* "I'm worthless" --> synchronize with the fade to black.
* begin nightmare murmuring in the middle of bedroom 1 --> crescendo to hallway 2

**Comment by mark-craig** [comment]
* Falling thud
* Layers for horse walking
* "I'm Worthless" --> remove

**Comment by mark-craig** [comment]
Did we decide to keep "I'm worthless" in the end? I'm pretty sure I heard everything else.

**Comment by pointyteeth** [comment]
I think we haven't had a critique without it yet...? Not sure, so let's try it without it again lol
