### ISSUE TITLE
Adjust Bedroom 1 Camera

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#17]
All cameras need to be tweaked, but these are the ones that I think are the most obviously in need of it:
* Bedroom 1, first shot needs to be zoomed out to reflect storyboard, show the set clearly

**Comment by mark-craig** [comment]
Meena is going to push some changes to the bedroom 1 shot where Emily is squirming in bed, so keep her posted on your progress. With that so there are no conflicts.

**Comment by pointyteeth** [comment]
I adjusted the two shots in Bedroom1, renders of them are in Week 3/videos :ice_cream:
