### ISSUE TITLE
Improve Bedroom 1 Set

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#21]
--- Kenny
* Books (same model, 3 or so sizes)
* Bed frame needs new model
--- Bernadette.
* Lamp needs to be modeled
* Bookcase needs sharper edgeloops, separated shelves.
--- Meena
* Model toy sword.
* Adjust real sword
@pointyteeth @Hermittamer @kennyw1019

**Comment by mark-craig** [comment]
I see @Hermittamer's pushes....I don't see any updates from @pointyteeth or @kennyw1019...

**Comment by pointyteeth** [comment]
I adjusted the real sword just now, and I see I've been assigned the bookshelf, I'll do that next~

**Comment by pointyteeth** [comment]
wait no someone updated that an hour ago

**Comment by pointyteeth** [comment]
what should I do @_@

**Comment by mark-craig** [comment]
Messaged you on facebook as well. Switch gears to Emily's hair mesh.

**Comment by mark-craig** [comment]
I think everything has been modeled. Good job guys! Marking this as closed.
