### ISSUE TITLE
Charge 1 Animation

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#22]
* First 3 seconds blocked out (unicorn helps Emily up).
* Overlapping camera jump.

**Comment by mark-craig** [comment]
Any updates on this? Sorry I missed last meeting.

**Comment by oliverzp** [comment]
Yeah I animated some stuff and got some notes to change it on Sunday. I haven't incorporated changes as much yet though

**Comment by mark-craig** [comment]
I think that we will need to work in parallel on this scene; we need some smoke simulation to indicate the monsters moving away as small vapors, and we need to start pushing ideas for sets/backgrounds. Can you push what you have so far? We should be able to handle the parallel work with references, but keep a local copy.
