### ISSUE TITLE
Polished School Environment - Hallway

### ISSUE THREAD

**Issue by oliverzp** [CNM190/Nightmare#26]

**Comment by mark-craig** [comment]
To clarify, I think that our timeline for the school should be as follows:

This week: 
@public-float-artMajor will create more detailed concept art, clearly showing tiny details and props that make the hallway more "school-like" (banners, posters, doors, etc.). Also any quick sketches you can provide on what exactly the environment decay will look like will be useful for....
@kennyw1019, who  will start by creating a basic decay effect on the locker prop. This will probably require a combination of blendshapes and keyframed textures. Let me know if you want to collaborate on this ^^

**Comment by mark-craig** [comment]
Going to give this an extra week.

**Comment by public-float-artMajor** [comment]
I ended up doing other polished art for the crossfade (though I have not received feedback still), so I will be making an issue for that and closing it under my name to receive credit and recognition for this task.

**Comment by public-float-artMajor** [comment]
Updated title so that I can split my pre-production tasks.
