### ISSUE TITLE
Test a bloom effect and nonphotorealistic effects in Nuke

### ISSUE THREAD

**Issue by pointyteeth** [CNM190/Nightmare#29]
... start by learning Nuke

**Comment by mark-craig** [comment]
This is obviously going to be long term, but what is a reasonable deadline for expecting a first attempt? I'm marking this for next week, but let me know if you feel like you will need more time.

**Comment by pointyteeth** [comment]
I think doing a bloom effect would be reasonable for this week :D I know how to do the actual effect, I just need to figure out how to do it in Nuke

**Comment by pointyteeth** [comment]
Done with the bloom effect!
This raises two questions:
1. Where, if anywhere, should Nuke files be stored for sharing?
2. Is it possible to hook post-processing into the render pipeline?

**Comment by mbdriscoll** [comment]
Sweet! Can you attach an example frame to this post, next to a non-modified one?
Regarding your questions:
1. Probably a second repo, such as "Nightmake-nuke".
2. Probably not easily. You can get close by writing a nuke script to automate our particular tasks.

**Comment by pointyteeth** [comment]
There's also a video on the Facebook page showing the effect :D
![bt1](https://cloud.githubusercontent.com/assets/1498428/6544107/6c951ba4-c4f2-11e4-9d34-b9327da82848.png)
![bt24](https://cloud.githubusercontent.com/assets/1498428/6544108/6c997802-c4f2-11e4-8ec5-c847dbd7b36a.png)

**Comment by mbdriscoll** [comment]
Hmm. It makes it look dream-like. @SaraSweer, do we want that effect in the non-nightmare shots? @pointyteeth, I'm putting updated frames in Google Drive > Spring 2015 HW > Nightmare > Frames if you want to play with those.

**Comment by mark-craig** [comment]
marking this as closed
