### ISSUE TITLE
Rig the dog

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#3]
Clyde needs a better armature. Candy's rig should be good reference for this (possibly the same rig?)

**Comment by mark-craig** [comment]
I think we will wait on this until we see if reusing Candy's rig is viable. Kenny also pointed out that the dog basically doesn't have to move except for maybe the neck. An alternative may be to model him in pose.

**Comment by public-float-artMajor** [comment]
Update:
- IK splines added to mimic curled back
- Ear joints added (if necessary)
- Front legs adjusted so that they bend in the proper direction
- Blendshapes for smile, eyebrow raise, and breathing added
