### ISSUE TITLE
Color scripts pt. 1

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#38]
We need basic color references for lighting and materials in our scenes.
The scene I think you should start with is Hallway 1. :)

**Comment by mark-craig** [comment]
![11032310_927894987263179_272694086_o](https://cloud.githubusercontent.com/assets/4493801/6660642/e4c31ba8-cb5a-11e4-846a-d6c144844342.jpg)

**Comment by public-float-artMajor** [comment]
5/8 mini boards for Draft 1 of the color scripts completed as of 3/22.

**Comment by public-float-artMajor** [comment]
SET 1:
![colorscript_set_resize1](https://cloud.githubusercontent.com/assets/4197056/7054997/33cf71cc-ddf5-11e4-98a0-4b4b11ba764e.png)

SET 2:
![colorscript_set_resize2](https://cloud.githubusercontent.com/assets/4197056/7054998/33d0b014-ddf5-11e4-99bd-9c3c72cc01dc.png)
