### ISSUE TITLE
Testing the Unicorn Rig

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#39]
So primarily putting this on Suchaaver @minifigmaster125  and Oliver @oliverzp , but anybody who is taking part in animation should try to help. Ryan has posted the first unicorn rig! Let's break it.

@public-float-artMajor has yet to do skinning on the back legs, some refined skinning on the front legs. Some things need to be hidden yet in the layers. Neck pivots also need to be moved. Other than that, the rig appears to be fully functional and is ready for testing.

Everyone please take the time to learn the rig, and try to see if there are any functional issues with the rig. E.G, are there any movements or actions that the unicorn either cannot do entirely, or cannot do without a great deal of extra animation.

**Comment by public-float-artMajor** [comment]
Thanks Suchaaver for actually taking the time to test this. :'D
