### ISSUE TITLE
Iterate on set changes. 

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#43]
Hallway is destroyed,  but reforms for fight scene?  Need to elaborate on this. Let's talk about different effects systems.

**Comment by mark-craig** [comment]
* Hallway should have a little more space than Leo's recent uploads, but not much. Basically, just tailored for the hallway 1 shot. 
* We should also reference the debris that Bernadette and Meena have modeled, start putting it in the scene.
* Let's start with creating the blue tint by adjusting the color emitted from the lights themselves.

![image](https://cloud.githubusercontent.com/assets/4493801/6660477/4598f352-cb57-11e4-9a05-3e7204237629.png)

**Comment by mark-craig** [comment]
Putting Ryan's artwork here for color reference:
![11032310_927894987263179_272694086_o](https://cloud.githubusercontent.com/assets/4493801/6660483/87449dd8-cb57-11e4-9d2c-8748d4d293a5.jpg)

**Comment by public-float-artMajor** [comment]
Gonna close both #54 and #43 when I finish set iterations.

**Comment by public-float-artMajor** [comment]
From #54 (closed it because of this issue):
- Iterate Meena's Charge1 idea
- Show transitional environment changes for all scenes (quick art)
- Work with voids ideas (make more abstract?)
