### ISSUE TITLE
Fix references for bedroom 2

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#6]
Right now Emily is imported. The scene will need to basically be set up again..

**Comment by mark-craig** [comment]
Emily's final pose from charge 3 needs to be retained, and /chars/Emily.ma should be the only reference to emily. The bedroom set should be changed from an import to a reference, since we will need to texture the set soon.

**Comment by mark-craig** [comment]
Looks good. NIce Job.

One thing that just occurred to me though is that the animation in charge 3 appears to still need some work. Her eyelids are thrown off by the blendshape I made earlier, so either that needs to be tweaked or the animation itself needs to be updated.

I said to reference Emily.ma, but now that I think about it maybe bedroom2 should just reference charge3, and everything other than Emily can be hidden. This may save some work down the line, what do you think?

**Comment by minifigmaster125** [comment]
Yeah,  it's really hard for me to close her eyes--her eyelids seem kinda 
-- broken. I'm not sure. I can definitely try referencing the whole 
charge 3 and just hide stuff on a layer.  It probably would save a lot 
of work.

**Comment by mark-craig** [comment]
Sounds good, I'll mark this as closed in the meantime.
