### ISSUE TITLE
Rig Nightmare Model

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#8]
Upper torso of Nightmare model needs to be rigged
* fingers should be able to move
* eyes should be rigged as well

**Comment by mark-craig** [comment]
Reopening based on the comments you gave me in lab. Will try to push the updated rig soon.

**Comment by oliverzp** [comment]
Can you also make the arms stretcable? Just let the translate channels on the controls affect the mesh

**Comment by mark-craig** [comment]
OK, will do.

**Comment by mark-craig** [comment]
Going to need a little more time on this...Mirroring the controls is not trivial while still keeping the orientations.

**Comment by mark-craig** [comment]
Yeah, I'm not sure if there is a good solution for this. I figure that frozen transformations is more important than correctly oriented object transforms, so I am just closing this and moving on to other things. If someone else wants to reopen this feel free :P
