### ISSUE TITLE
Emily Texture

### ISSUE THREAD

**Issue by mark-craig** [CNM190/Nightmare#9]
Color map for emily needs to be refined/replaced.
* Realistic blush on cheeks
* Freckles/Moles/other details
* Slight variation in skin tone

**Comment by mark-craig** [comment]
After the discussion on Meet Buck, I think that we should avoid overly obvious brush strokes. It may not be feasible to paint a map that looks good in every scene (they may have repainted the texture for each scene in MB). We should look into achieving the painterly style through post processing, shaders, or another non-manual approach.

**Comment by mark-craig** [comment]
Reopening to retexturing the body.
* Coloration on palms, elbows.

**Comment by pointyteeth** [comment]
Done!
